version: '3.3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules  # Только node_modules, чтобы избежать перезаписи собранных файло
      - upload:/home/node/app/uploads
    env_file:
      - .env  # Подключаем .env файл
    depends_on:
      - db
      - redis
    command: ["sh", "-c", "npx sequelize-cli db:migrate && npm start"]  # Выполнение миграций, затем запуск с dist

  
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'

volumes:
  db_data:
  upload: